### ISSUE TITLE
A question about the installation steps

### ISSUE THREAD

**Issue by jack-tan** [Systems-Modeling/SysML-v2-Pilot-Implementation#184]
I encountered a problem during the installation. What is the third step? I tried many methods, but still did not solve it.help me!
![q3](https://user-images.githubusercontent.com/22318547/103183719-35af5a00-48ef-11eb-858b-e1187794735b.png)

**Comment by aweirose** [comment]
I also encountered the same problem, unable to display the model diagram successfully

**Comment by seidewitz** [comment]
@jack-tan 
In the runnning Eclipse instance:

1. Select `Window > Show View > Other...`.
2. In the `Show View` window, select `Git > Git Repositories` and click `Open`.
3. In the  `Git Repositories` view, select "Add an existing local Git Repository to this view" (![image](https://user-images.githubusercontent.com/8561049/103227301-0226fc80-48fc-11eb-8ec5-fdc882fc73ca.png) button).
4. Enter the directory into which you cloned the `SysML-v2-Pilot-Implementation` repository.
5. Select the repository and click `Add`.

**Comment by jack-tan** [comment]
Thank you very much for answering this question for me, and follow your answers. I have completed the installation and will show or draw a simple case. But is this software unstable? Or for other reasons. When creating a case, when referencing types in other sysml or kerml files, sometimes it can be quoted (and no error is reported), but sometimes an error is reported, and the system restarts. It will be good, and it will be bad, as shown in the following two pictures
![image](https://user-images.githubusercontent.com/22318547/103534003-0db08f80-4ec9-11eb-8713-6b2c67eb6eb7.png)
![image](https://user-images.githubusercontent.com/22318547/103534059-23be5000-4ec9-11eb-9242-5afab4e229a8.png)

**Comment by seidewitz** [comment]
This is a prototype implementation still in ongoing development, provided as-is for community use. We do try to make each monthly release stable for use, but there are bound to be problems sometimes. Simple bugs can usually be resolved in time for the next monthly release, but we are also in the process of a deeper multi-month refactoring to address some deeper issues with the current design.

That said, the errors you have highlighted typically result from not having the model libraries properly configured for global name resolution. In addition to explicit imports, implicit references to library elements are inserted in many places as model text is parsed (for instance, that can cause errors in the validation of multiplicities, as you have shown).

Before you opened a model using the KerML or SysML editors, did you carefully follow steps 4 to 7 under "Getting started" in the README?

> 4. Turn off Project > Build Automatically.
> 
> 5. Import the projects `kerml`, `sysml` and `sysml.library` into the runtime Eclipse workspace. (See the following section if you wish to create additional projects.)
> 
> 6. Execute Project > Clean with the following settings:
>    * Clean all projects: *Not* selected
>    * `sysml.library`: Selected
>    * Start a build immediately: Selected
>    * Build only the selected projects: Selected
> 
> 7. Repeat Project > Clean as above for `kerml` and `sysml`.
> 
>    **Important:** Be sure to first build *only* `sysml.library` before building `kerml` or `sysml`.

If you have created a new project for your model files, did you follow steps 6 and 7 under "Initializing New SysML Model Projects"?

> 4. On the Project References page, check the `sysml.library` project. This step tells Eclipse which other projects should be visible for resolving cross-references.
> 
> 5. Right-click the new project and select Configure > Convert to an Xtext project. This step sets up the indexing infrastructure necessary for resolving references between different files.

Not carrying out these steps properly can lead to the kind of errors you are seeing. If, after following these steps, you are still seeing errors, then this can sometimes be resolved by closing all editor tabs and re-doing the clean build steps, starting with `sysml.library`.

**Comment by seidewitz** [comment]
@jack-tan
I was just checking to see if you have been able to resolve the remaining problems with our installation.

**Comment by jack-tan** [comment]
I am very grateful for your help. With your help, I have successfully installed sysml v2 and built related cases. The unstable situation of the system has also been resolved. However, there is a new question about SysML V2 model extension (similar to the extension of UML profile), based on sysml v2, based on block definition diagrams, internal block diagrams, and state machines. I want to build a language for domain specific language, but in "SysML-v2-Part-2-OMG_Systems_Modeling_Language_(SysML)-2020-09.pdf"  not provide the corresponding information. I'd like to acquire all the information relative to the extension of SysML V2, you can provide some information or some materials

**Comment by seidewitz** [comment]
Glad to hear things are working!

Being able to build domain specific languages on top of SysML v2 is an important goal for the language. However, while we have discussed the requirements and various possible approaches for designing this capability, we are only now at the point of actually being able to start implementing something. There will be a small step toward this in the 2020-12 release, with an initial capability for simple metadata annotations. We hope to have something more extensive implemented over the next couple of months.

If you would inquire further about our current plans for the language extension capability, or start a discussion on creating domain specific languages built on SysML v2, I would encourage you to join the Google Group at [https://groups.google.com/g/sysml-v2-release](https://groups.google.com/g/sysml-v2-release).
