### ISSUE TITLE
Clarify %viz arguments in Intro to SysML and Jupyter console

### ISSUE THREAD

**Issue by fitzgeraldsystems** [Systems-Modeling/SysML-v2-Pilot-Implementation#201]
I'm using SysML v2 Release 2020-12 and trialing SysML v2 on Jupyter Labs and wanted to visualize connections. I copied and pasted the code for ./sysml/src/training/10. Connections/Connections Example.sysml to my jupyter notebook.

I ran `%viz Namespace::Element` which gave a tree view. It took me some searching to figure out that `%viz` takes the `--view` argument.

Suggestions:
1.  In the Intro to SysML v2 document to include a slide that explains how to realize the different views in Jupyter.
2. Give `%viz` an argument of `--help` or something similarly intuitive that can output to Jupyter console a short description on how to use the `%viz` command.

For other people taking SysML v2 for a trial run they are:

For a tree view or similar view to BDD
`%viz --view=tree Namespace::Element`
For a state view
`%viz --view=state Namespace::Element`
For a view of interconnections or similar view to IBD
`%viz --view=interconnection Namespace::Element`
For a view of actions
`%viz --view=action Namespace::Element`
For a view of sequences
`%viz --view=sequence Namespace::Element`
For a default view (I assume that SysML takes the element type to infer the type of view)
`%viz --view=default Namespace::Element` which is the same as `%viz Namespace::Element`

**Comment by himi** [comment]
I agree that --help or -h option and "%viz" only should show some help messages.  Quick and corner-cutting solution is easy but I18N should be considered in the future.

**Comment by seidewitz** [comment]
This is resolved in release [2021-03](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases/tag/2021-03a). The `%viz -h` command now prints a brief description of the usage of and options for `%viz`.
