### ISSUE TITLE
Decision node plantUML issue

### ISSUE THREAD

**Issue by rubinho101** [Systems-Modeling/SysML-v2-Pilot-Implementation#204]
I am using the Eclipse pilot implementation. What is the proper syntax for a decision node / if clause to be visualized in PlantUML?

Even the decision node example of the Intro PDF (p. 43) is not working.

Any ideas?

Thx

**Comment by seidewitz** [comment]
This seems to be a bug. I have reported it internally for resolution.

**Comment by rubinho101** [comment]
Thanks, looking forward for the update. A couple more questions @seidewitz :

- when will there be a more detailed syntax documentation available? eg. how to merge several if-paths, how to extend kerml/sysml. 
- Are there more documents available than on https://github.com/Systems-Modeling/SysML-v2-Release/tree/master/doc ? eg. RFC.

**Comment by seidewitz** [comment]
Please re-post your questions on the [SysML v2 Release](https://groups.google.com/g/sysml-v2-release) Google Group. This GitHub issue will be closed after the originally identified bug is fixed in the coming 2020-02 release.

**Comment by seidewitz** [comment]
This issue is resolved in release 2021-02.
