### ISSUE TITLE
Plant UML Diagram not visible

### ISSUE THREAD

**Issue by Martin-Bohring** [Systems-Modeling/SysML-v2-Pilot-Implementation#265]
Hello,
I have got the pilot implementation running based on your description.
Everything I tried works except the Plant UML rendering is always empty.

I have installed [https://graphviz.org/](https://graphviz.org/).

Is Plant UML support build in or do I also have to install [https://plantuml.com/](https://plantuml.com/)?

**Comment by himi** [comment]
Which tool of Jupyter or Eclipse did you install?  More detailed explanation on what you did will help me understand the situation.  If you manually install in Eclipse environment without oomph, you need to manually install it from https://github.com/himi/p2-update-puml-sysmlv2/raw/main/updates as written in Step 1 of README.

**Comment by seidewitz** [comment]
I am closing this issue, since there has been no follow up on it since August. Please see also the resolution to the related issue https://github.com/Systems-Modeling/SysML-v2-Release/issues/41.
