### ISSUE TITLE
Derived feature related method naming problems in RequirementUsageImpl

### ISSUE THREAD

**Issue by grbeni** [Systems-Modeling/SysML-v2-Pilot-Implementation#329]
In class `RequirementUsageImpl`,  the implementation of methods `getRequiredConstraint()` and `getAssumedConstraint()` is probably swapped, as the former references the ˙`RequirementConstraintKind.ASSUMPTION` literal, and the latter the `RequirementConstraintKind.REQUIREMENT` for filtering `ConstraintUsages`:
https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/56d0fdf23f54bf9fd00589635c6886e6d3a0d0d1/org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/RequirementUsageImpl.java#L262

A potential solution could be to swap the method names or the implementations.

**Comment by seidewitz** [comment]
You are right, these methods are exactly backwards! I will submit a bug report, so it will be fixed in the next release.

Thanks for identifying this.

**Comment by seidewitz** [comment]
This is fixed in [release 2022-02](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases/tag/2022-02) (see also PR #331).
