### ISSUE TITLE
Derived feature related type filtering problem in DefinitionImpl

### ISSUE THREAD

**Issue by grbeni** [Systems-Modeling/SysML-v2-Pilot-Implementation#334]
In class `DefinitionImpl`, the implementation of method `getOwnedConnection` filters and returns objects of type `ConnectionUsage` even though the method signature specifies `EList<ConnectorAsUsage>` as return value type:

https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/56d0fdf23f54bf9fd00589635c6886e6d3a0d0d1/org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/DefinitionImpl.java#L195

 The code works as `ConnectorAsUsage` is a super interface of `ConnectionUsage`, but this way, owned objects of other classes implementing other subinterfaces of  `ConnectorAsUsage`, e.g., `BindingConnectorAsUsage`, cannot be retrieved via this method, or any other method of this class.

**Comment by seidewitz** [comment]
You are correct. This should have been updated a few releases ago. I will submit a bug report for it.

**Comment by seidewitz** [comment]
This is fixed in [release 2022-02](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases/tag/2022-02) (see also PR #335 ).
