### ISSUE TITLE
problem about sysml v2 language textual notation.pdf

### ISSUE THREAD

**Issue by wingsdouble** [Systems-Modeling/SysML-v2-Pilot-Implementation#339]
From the Root-Root syntactic elements section in the Four-Layer Language Architecture on the fourth page of your sysml v2 language textual notation, we can see the TextualAnnotation element. However, no matter in sysml v2 release or from sysml ecore of piloat, we only found TextualRepresentation, so, is it changed to TextualRepresentation?

**Comment by seidewitz** [comment]
The slide in the Textual Notation training material is incorrect. TextualRepresentation is correct. This will be corrected in the next release.

**Comment by seidewitz** [comment]
This is corrected in the [training material for release 2022-02](https://github.com/Systems-Modeling/SysML-v2-Release/tree/master/doc).
