### ISSUE TITLE
202208Release cannot display connection symbol correctly

### ISSUE THREAD

**Issue by Canvis-Me** [Systems-Modeling/SysML-v2-Pilot-Implementation#399]
Hello, I installed 202208 [SysML-v2-Release](https://github.com/Systems-Modeling/SysML-v2-Release) in both eclipse and jupyter, and found some connection/flow symbol cannot display. However the same .sysml file can be rendered in 202207 version. The test file was "sysml/src/training/14. Action Definitions/Action Succession Example-2.sysml".

202208:
![ActionSuccessionExample2](https://user-images.githubusercontent.com/55122738/191777778-67ed9cbd-137c-47db-a782-35993da0d5f0.png)

202207:
![ActionSuccessionExample2-2207](https://user-images.githubusercontent.com/55122738/191777834-9b62aeb9-c22b-4bd1-ad51-d0999b7da695.png)

So how can I display the connection/flow symbol in 202208 version?

**Comment by himi** [comment]
Thanks. It is already reported in the internal tracking system (Jira).  I'll fix it in the next release (almost done in ST6RI-596)

**Comment by Canvis-Me** [comment]
Thank you!
