### ISSUE TITLE
KerML::Element vs KerML::Root::Element

### ISSUE THREAD

**Issue by Rots** [Systems-Modeling/SysML-v2-Pilot-Implementation#418]
I think there's a problem in the KerML files, apparently the `KerML::Element` was moved to `KerML::Root::Element` (in https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/2022-09/sysml.library/Kernel%20Libraries/Kernel%20Semantic%20Library/KerML.kerml#L31) but it's still referenced with the old name in here

https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/2022-09/sysml.library/Kernel%20Libraries/Kernel%20Semantic%20Library/Metaobjects.kerml#L9

**Comment by seidewitz** [comment]
All of the `KerML` subpackages are imported into and re-exported from the top-level `KerML` package. So, all KerML metaclasses can still be referenced using only the `KerML::` qualification (like `KerML::Element`).

**Comment by Rots** [comment]
OK, I missed the transitive imports. Then this is a non-issue.
