### ISSUE TITLE
start and done symbol don't display

### ISSUE THREAD

**Issue by Canvis-Me** [Systems-Modeling/SysML-v2-Pilot-Implementation#424]
It seems that `sysml\src\training\17. Control\Decision Example.sysml` doesn't show `start` and `done` element in diagram, other control node works well.

**Comment by himi** [comment]
Thank you for the report.  I found entry and exit actions in states are not rendered.  I'll fix it in the next sprint.

**Comment by Canvis-Me** [comment]
Thanks, the pr version works fine now.
