### ISSUE TITLE
Error installing jupyter notebook

### ISSUE THREAD

**Issue by the-jan-peter** [Systems-Modeling/SysML-v2-Pilot-Implementation#427]
At[ MBSE22 De Koning ](https://indico.esa.int/event/407/timetable/#42-sysml-version-2-final-stret)presented yesterday the usage of SysMLv2 code->graphic translator using Jupyter Notebooks.

Looking at the Pilot Implementation Repo, I guess I would have to use the[ jupyter notebook installer](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/tree/master/org.omg.sysml.jupyter.installer)

Cloning the complete pilot repo and then following the README in the mentioned directory offers me the following error:

```
$ ./install.sh
./install.sh: 24: Bad substitution
```

The referred line in the install script:

`
SYSML_VERSION="${project.version.unqualified}"`

Any help in visualising sysml code into graphics is highly welcomed!

**Comment by Canvis-Me** [comment]
Try https://github.com/Systems-Modeling/SysML-v2-Release/blob/aefe04e5124157ce2ed32041ee5cadb081ccdc15/install/jupyter/README.pdf

The release files are from https://github.com/Systems-Modeling/SysML-v2-Release.

**Comment by seidewitz** [comment]
@Canvis-Me has the correct reference for doing a Jupyter installation of the latest public release. 

The projects in the SysML v2 Pilot Implementation repository are for development, and the install scripts in `org.omg.sysml.jupyter.installer` are actually the templates for the scripts included in the release. If you want to do an installation from the development repository, you would first need to do a clean Maven build on the entire repository, and then find the generated snapshot install subdirectory under the resulting `org.omg.sysml.jupyter.installer/target` directory.

Unless you want to do some development updates, it is better to use the release install directory! 🙂
