### ISSUE TITLE
How to use user created sysml library other than standard built in library in jupyter notebook

### ISSUE THREAD

**Issue by dum3ng** [Systems-Modeling/SysML-v2-Pilot-Implementation#430]
After install the jupyter sysml kernel, I can import the standard library in jupyter notebook. 
But how can import library created by myself?

I have tried to place the my local sysml library file into the jupyter sysml kernel installation location, alongside with the `sysml.library`, but still can not import them.

**Comment by himi** [comment]
TTBOMK, just putting sysml files to the current directory could not be resolved by Jupyter notebooks unlike other standard libraries. It's a critical issue on modularized modelings.  The library load path is fixed to the subdirectories of `sysml.library`.  So `.sysml` files in for example `Domain Libraries`  will be loaded at the startup of the Jupyter kernel.

Based on this SysMLv2 Jupyter implementation, I'm developing the integrated modelling environment, called Mg, providing autoload functionality, which look up sysml files to resolve names in the global scopes.  I'm working on it to make it public but it will not be an open source at least for the time being.

**Comment by Canvis-Me** [comment]
Oh yes, you're right. I forgot that each time when I want to import user library, I would paste the library files to the sysml kernel console and press `Shift+Enter` to make it work for other files.

**Comment by seidewitz** [comment]
The SysML kernel for Jupyter was not really designed to allow adding user-defined libraries. However, as @himi noted, if you place `.sysml` files under the `sysml.library/Domain Libraries` subdirectory, they should be read in when a SysML notebook is opened. Having a better capability for user libraries would certainly be useful, and it has been discussed internally, but it has not been a development priority as we try to complete our specification deliverables for submission to OMG.

**Comment by dum3ng** [comment]
**Summary**: place the `.sysml` file to `miniconda3\share\jupyter\kernels\sysml\sysml.library` to import.
And if want to reload the files from change, select `kernel - restart kernel` to reload files.

**Comment by smp4** [comment]
For anyone coming to this for the future, another solution is to use symlinks. 

I created a Python [Cookiecutter](https://www.cookiecutter.io/) template to set up a SysML development environment using VS Code, SysIDE and Jupyter with the Pilot Implementation Jupyter SysML kernel. It uses symlinks to provide user models to the kernel, it works quite well. The template is available at [sysmlv2-python-cookiecutter](https://github.com/smp4/sysmlv2-python-cookiecutter).
