### ISSUE TITLE
Missing documentation on various eStructuralFeatures in the SysML.ecore file

### ISSUE THREAD

**Issue by samatrhea** [Systems-Modeling/SysML-v2-Pilot-Implementation#472]
While using the SysML.ecore file for codegeneration purposes i have noticed that a number of properties in classes are missing documentation, see list below:

Feature:isNonunique
MetadataUsage:metadataDefinition
OperatorExpression:operand
ViewRenderingMembership:ownedRendering

Perhaps you would like to include some docs in the source UML model and regenerate the Ecore model including the `missing` docs.

**Comment by seidewitz** [comment]
`Feature::isNonunique` and `OperatorExpression::operand` are added to `SysML.ecore` for implementation reasons. They are not in the normative abstract syntax and do not appear in `SysML.uml`.

The two other properties you mentioned (and, hopefully, all the other properties in the metamodel) now have documentation.

**Comment by samatrhea** [comment]
Hi @seidewitz

I can confirm that all other properties have docs, using the following code to inspect that: https://github.com/RHEAGROUP/SysML2.NET/blob/0909eca4347f0c03336dfe55ee73b7636239d6f2/SysML2.NET.CodeGenerator/Inspector/ModelInspector.cs#L226

Thanks for updating the metamodel for the next release
