### ISSUE TITLE
Include textx version of pilot implementation

### ISSUE THREAD

**Issue by danyeaw** [Systems-Modeling/SysML-v2-Pilot-Implementation#481]
I've been working on converting the xtext to textx so that I can generate a data model in Python for Gaphor. Would you be open to including this as part of pilot implementation?

**Comment by seidewitz** [comment]
Probably not at this time. 

Now that the specifications have been submitted to OMG, we are in the process of transitioning the pilot implementation to a reference implementation and deciding how it will be managed in the future. Our focus right now is on updating the implementation to rigorously conform to the specifications and tracking the OMG finalization process for the specifications.

Going forward, however, we would certainly be interested in alternatives to Xtext as a parsing framework for the reference implementation. But only in the context of a complete language implementation, including name resolution, validation, derived property computation and semantic relationships with the standard library models.

That said, we would still encourage you to make your work available to the community, whether or not it is part of the pilot/reference implementation.

**Comment by danyeaw** [comment]
Thanks @seidewitz
