### ISSUE TITLE
jupyterlab>=4 fails building jupyterlab-sysml extension

### ISSUE THREAD

**Issue by GorgiAstro** [Systems-Modeling/SysML-v2-Pilot-Implementation#524]
It looks like jupyterlab version >= 4 does not manage to build the jupyterlab-sysml extension. 

I just tested with my old jupyterlab version 3.6.6 , it built the extension successfully. After upgrading to version 4.0.10 however, I get the following error when jupyterlab tries to build the extension (this is from the jupyterlab debug log):

> 
> [LabBuildApp] Building in /opt/conda/share/jupyter/lab
> [LabBuildApp] Node v20.9.0
> 
> [LabBuildApp] Yarn configuration loaded.
> [LabBuildApp] Building jupyterlab assets (production, minimized)
> [LabBuildApp] > node /opt/conda/lib/python3.11/site-packages/jupyterlab/staging/yarn.js install
> [LabBuildApp] ➤ YN0000: ┌ Resolution step
> ➤ YN0002: │ @jupyterlab/application-top@workspace:. doesn't provide codemirror (pa58b9), requested by @systems-modeling/jupyterlab-sysml
> ➤ YN0002: │ @jupyterlab/cell-toolbar-extension@npm:4.0.9 doesn't provide react (pf2141), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/console-extension@npm:4.0.9 doesn't provide react (pc2341), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/csvviewer-extension@npm:4.0.9 doesn't provide react (pf2b83), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/debugger-extension@npm:4.0.9 doesn't provide react (p42cf6), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/documentsearch-extension@npm:4.0.9 doesn't provide react (p5b112), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/extensionmanager-extension@npm:4.0.9 doesn't provide react (p2812f), requested by @jupyterlab/settingregistry
> ➤ YN0060: │ @jupyterlab/extensionmanager@npm:4.0.9 provides react (pa03d2) with version 18.2.0, which doesn't satisfy what react-paginate requests
> ➤ YN0002: │ @jupyterlab/filebrowser-extension@npm:4.0.9 doesn't provide react (p70a5b), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/fileeditor-extension@npm:4.0.9 doesn't provide react (p02cb1), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/htmlviewer-extension@npm:4.0.9 doesn't provide react (pb6ffe), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/json-extension@npm:4.0.9 doesn't provide @types/react (p0b2d9), requested by react-json-tree
> ➤ YN0002: │ @jupyterlab/mainmenu-extension@npm:4.0.9 doesn't provide react (p73fdb), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/markdownviewer-extension@npm:4.0.9 doesn't provide react (p0800d), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/metadataform-extension@npm:4.0.9 doesn't provide react (p98121), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/metadataform@npm:4.0.9 doesn't provide @rjsf/utils (peac99), requested by @rjsf/core
> ➤ YN0002: │ @jupyterlab/metadataform@npm:4.0.9 doesn't provide @rjsf/utils (p69871), requested by @rjsf/validator-ajv8
> ➤ YN0002: │ @jupyterlab/services@npm:7.0.9 doesn't provide react (p89091), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/settingeditor-extension@npm:4.0.9 doesn't provide react (p30a92), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/statusbar-extension@npm:4.0.9 doesn't provide react (p8e383), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/terminal-extension@npm:4.0.9 doesn't provide react (p7976c), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/toc-extension@npm:6.0.9 doesn't provide react (p0efb9), requested by @jupyterlab/settingregistry
> ➤ YN0002: │ @jupyterlab/translation-extension@npm:4.0.9 doesn't provide react (pd0328), requested by @jupyterlab/settingregistry
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed in 0s 493ms
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed in 0s 576ms
> ➤ YN0000: ┌ Link step
> ➤ YN0000: └ Completed in 0s 710ms
> ➤ YN0000: Done with warnings in 1s 911ms
> 
> [LabBuildApp] > node /opt/conda/lib/python3.11/site-packages/jupyterlab/staging/yarn.js dlx yarn-berry-deduplicate -s fewerHighest --fail
> [LabBuildApp] ➤ YN0000: ┌ Resolution step
> ➤ YN0000: └ Completed in 5s 853ms
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Link step
> ➤ YN0000: └ Completed in 1s 341ms
> ➤ YN0000: Done in 7s 369ms
> 
> No duplicates found, yarn.lock identical
> 
> [LabBuildApp] > node /opt/conda/lib/python3.11/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
> [LabBuildApp] [webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'codemirror' in '/opt/conda/share/jupyter/lab/staging/node_modules/@systems-modeling/jupyterlab-sysml/build'
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:2016:28
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:798:13
>     at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:270:22
>     at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:434:22
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:116:11
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:670:25
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:855:8
>     at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:975:5
> resolve 'codemirror' in '/opt/conda/share/jupyter/lab/staging/node_modules/@systems-modeling/jupyterlab-sysml/build'
>   Parsed request is a module
>   using description file: /opt/conda/share/jupyter/lab/staging/node_modules/@systems-modeling/jupyterlab-sysml/package.json (relative path: ./build)
>     Field 'browser' doesn't contain a valid alias configuration
>     resolve as module
>       /opt/conda/share/jupyter/lab/staging/node_modules/@systems-modeling/jupyterlab-sysml/build/node_modules doesn't exist or is not a directory
>       /opt/conda/share/jupyter/lab/staging/node_modules/@systems-modeling/jupyterlab-sysml/node_modules doesn't exist or is not a directory
>       /opt/conda/share/jupyter/lab/staging/node_modules/@systems-modeling/node_modules doesn't exist or is not a directory
>       /opt/conda/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
>       looking for modules in /opt/conda/share/jupyter/lab/staging/node_modules
>         single file module
>           using description file: /opt/conda/share/jupyter/lab/staging/package.json (relative path: ./node_modules/codemirror)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               /opt/conda/share/jupyter/lab/staging/node_modules/codemirror doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               /opt/conda/share/jupyter/lab/staging/node_modules/codemirror.js doesn't exist
>             .json
>               Field 'browser' doesn't contain a valid alias configuration
>               /opt/conda/share/jupyter/lab/staging/node_modules/codemirror.json doesn't exist
>             .wasm
>               Field 'browser' doesn't contain a valid alias configuration
>               /opt/conda/share/jupyter/lab/staging/node_modules/codemirror.wasm doesn't exist
>         /opt/conda/share/jupyter/lab/staging/node_modules/codemirror doesn't exist
>       /opt/conda/share/jupyter/lab/node_modules doesn't exist or is not a directory
>       /opt/conda/share/jupyter/node_modules doesn't exist or is not a directory
>       /opt/conda/share/node_modules doesn't exist or is not a directory
>       /opt/conda/node_modules doesn't exist or is not a directory
>       /opt/node_modules doesn't exist or is not a directory
>       /node_modules doesn't exist or is not a directory
> 
> [LabBuildApp] JupyterLab failed to build
> [LabBuildApp] ERROR | Build failed.
> Troubleshooting: If the build failed due to an out-of-memory error, you
> may be able to fix it by disabling the `dev_build` and/or `minimize` options.
> 
> If you are building via the `jupyter lab build` command, you can disable
> these options like so:
> 
> jupyter lab build --dev-build=False --minimize=False
> 
> You can also disable these options for all JupyterLab builds by adding these
> lines to a Jupyter config file named `jupyter_config.py`:
> 
> c.LabBuildApp.minimize = False
> c.LabBuildApp.dev_build = False
> 
> If you don't already have a `jupyter_config.py` file, you can create one by
> adding a blank file of that name to any of the Jupyter config directories.
> The config directories can be listed by running:
> 
> jupyter --paths
> 
> Explanation:
> 
> - `dev-build`: This option controls whether a `dev` or a more streamlined
> `production` build is used. This option will default to `False` (i.e., the
> `production` build) for most users. However, if you have any labextensions
> installed from local files, this option will instead default to `True`.
> Explicitly setting `dev-build` to `False` will ensure that the `production`
> build is used in all circumstances.
> 
> - `minimize`: This option controls whether your JS bundle is minified
> during the Webpack build, which helps to improve JupyterLab's overall
> performance. However, the minifier plugin used by Webpack is very memory
> intensive, so turning it off may help the build finish successfully in
> low-memory environments.
> 
> [LabBuildApp] Traceback (most recent call last):
> 
> [LabBuildApp]   File "/opt/conda/lib/python3.11/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
>     yield
> 
> [LabBuildApp]   File "/opt/conda/lib/python3.11/site-packages/jupyterlab/labapp.py", line 206, in start
>     raise e
> 
> [LabBuildApp]   File "/opt/conda/lib/python3.11/site-packages/jupyterlab/labapp.py", line 197, in start
>     build(
> 
> [LabBuildApp]   File "/opt/conda/lib/python3.11/site-packages/jupyterlab/commands.py", line 507, in build
>     return handler.build(
>            ^^^^^^^^^^^^^^
> 
> [LabBuildApp]   File "/opt/conda/lib/python3.11/site-packages/jupyterlab/commands.py", line 723, in build
>     raise RuntimeError(msg)
> 
> [LabBuildApp] RuntimeError: JupyterLab failed to build

Environment:

* Ubuntu 22.04 amd64
* I tried both in a docker image and directly in Ubuntu
* jupyterlab-sysml version 0.37. 
* conda environment:

> \# packages in environment at /opt/conda:
> \#
> \# Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       2_gnu    conda-forge
> aiosqlite                 0.19.0             pyhd8ed1ab_0    conda-forge
> alembic                   1.13.1             pyhd8ed1ab_0    conda-forge
> alsa-lib                  1.2.10               hd590300_0    conda-forge
> anyio                     4.2.0              pyhd8ed1ab_0    conda-forge
> archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
> argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
> argon2-cffi-bindings      21.2.0          py311h459d7ec_4    conda-forge
> arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
> asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
> async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
> async_generator           1.10                       py_0    conda-forge
> atk-1.0                   2.38.0               hd4edc92_1    conda-forge
> attrs                     23.1.0             pyh71513ae_1    conda-forge
> babel                     2.14.0             pyhd8ed1ab_0    conda-forge
> beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
> bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
> blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
> boltons                   23.1.1             pyhd8ed1ab_0    conda-forge
> brotli-python             1.1.0           py311hb755f60_1    conda-forge
> bzip2                     1.0.8                hd590300_5    conda-forge
> c-ares                    1.24.0               hd590300_0    conda-forge
> ca-certificates           2023.11.17           hbcca054_0    conda-forge
> cached-property           1.5.2                hd8ed1ab_1    conda-forge
> cached_property           1.5.2              pyha770c72_1    conda-forge
> cairo                     1.18.0               h3faef2a_0    conda-forge
> certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
> certipy                   0.1.3                      py_0    conda-forge
> cffi                      1.16.0          py311hb3a22ac_0    conda-forge
> charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
> colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
> comm                      0.1.4              pyhd8ed1ab_0    conda-forge
> conda                     23.11.0         py311h38be061_1    conda-forge
> conda-libmamba-solver     23.12.0            pyhd8ed1ab_0    conda-forge
> conda-package-handling    2.2.0              pyh38be061_0    conda-forge
> conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
> configurable-http-proxy   4.6.1                h92b4e83_0    conda-forge
> cryptography              41.0.7          py311hcb13ee4_1    conda-forge
> debugpy                   1.8.0           py311hb755f60_1    conda-forge
> decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
> defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
> distro                    1.8.0              pyhd8ed1ab_0    conda-forge
> entrypoints               0.4                pyhd8ed1ab_0    conda-forge
> exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
> executing                 2.0.1              pyhd8ed1ab_0    conda-forge
> expat                     2.5.0                hcb278e6_1    conda-forge
> fmt                       10.1.1               h00ab1b0_1    conda-forge
> font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
> font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
> font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
> font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
> fontconfig                2.14.2               h14ed4e7_0    conda-forge
> fonts-conda-ecosystem     1                             0    conda-forge
> fonts-conda-forge         1                             0    conda-forge
> fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
> freetype                  2.12.1               h267a509_2    conda-forge
> fribidi                   1.0.10               h36c2ea0_0    conda-forge
> gdk-pixbuf                2.42.10              h829c605_4    conda-forge
> gettext                   0.21.1               h27087fc_0    conda-forge
> giflib                    5.2.1                h0b41bf4_3    conda-forge
> gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
> gitpython                 3.1.40             pyhd8ed1ab_0    conda-forge
> gmp                       6.3.0                h59595ed_0    conda-forge
> graphite2                 1.3.13            h58526e2_1001    conda-forge
> graphviz                  9.0.0                h78e8752_1    conda-forge
> greenlet                  3.0.3           py311hb755f60_0    conda-forge
> gtk2                      2.24.33              h7f000aa_3    conda-forge
> gts                       0.7.6                h977cf35_4    conda-forge
> harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
> icu                       73.2                 h59595ed_0    conda-forge
> idna                      3.6                pyhd8ed1ab_0    conda-forge
> importlib-metadata        7.0.1              pyha770c72_0    conda-forge
> importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
> importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
> ipykernel                 6.26.0             pyhf8b6a83_0    conda-forge
> ipython                   8.19.0             pyh707e725_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> ipywidgets                8.1.1                    pypi_0    pypi
> isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
> jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
> jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
> json5                     0.9.14             pyhd8ed1ab_0    conda-forge
> jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
> jsonpointer               2.4             py311h38be061_3    conda-forge
> jsonschema                4.20.0             pyhd8ed1ab_0    conda-forge
> jsonschema-specifications 2023.11.2          pyhd8ed1ab_0    conda-forge
> jsonschema-with-format-nongpl 4.20.0             pyhd8ed1ab_0    conda-forge
> jupyter-collaboration     2.0.1              pyhd8ed1ab_0    conda-forge
> jupyter-lsp               2.2.1              pyhd8ed1ab_0    conda-forge
> jupyter-server-mathjax    0.2.6              pyh5bfe37b_1    conda-forge
> jupyter-sysml-kernel      0.37.0             pyhd8ed1ab_0    conda-forge
> jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
> jupyter_core              5.5.1           py311h38be061_0    conda-forge
> jupyter_events            0.9.0              pyhd8ed1ab_0    conda-forge
> jupyter_server            2.12.1             pyhd8ed1ab_0    conda-forge
> jupyter_server_fileid     0.9.1              pyhd8ed1ab_0    conda-forge
> jupyter_server_terminals  0.5.0              pyhd8ed1ab_0    conda-forge
> jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
> jupyter_ydoc              2.0.1              pyhd8ed1ab_0    conda-forge
> jupyterhub                4.0.2              pyh31011fe_0    conda-forge
> jupyterhub-base           4.0.2              pyh31011fe_0    conda-forge
> jupyterlab                4.0.9              pyhd8ed1ab_0    conda-forge
> jupyterlab-git            0.50.0             pyhd8ed1ab_0    conda-forge
> jupyterlab-widgets        3.0.9                    pypi_0    pypi
> jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
> jupyterlab_server         2.25.2             pyhd8ed1ab_0    conda-forge
> keyutils                  1.6.1                h166bdaf_0    conda-forge
> krb5                      1.21.2               h659d440_0    conda-forge
> lcms2                     2.16                 hb7c19ff_0    conda-forge
> ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
> lerc                      4.0.0                h27087fc_0    conda-forge
> libarchive                3.7.2                h2aa1ff5_1    conda-forge
> libcups                   2.3.3                h4637d8d_4    conda-forge
> libcurl                   8.5.0                hca28451_0    conda-forge
> libdeflate                1.19                 hd590300_0    conda-forge
> libedit                   3.1.20191231         he28a2e2_2    conda-forge
> libev                     4.33                 hd590300_2    conda-forge
> libexpat                  2.5.0                hcb278e6_1    conda-forge
> libffi                    3.4.2                h7f98852_5    conda-forge
> libgcc-ng                 13.2.0               h807b86a_3    conda-forge
> libgd                     2.3.3                h119a65a_9    conda-forge
> libglib                   2.78.3               h783c2da_0    conda-forge
> libgomp                   13.2.0               h807b86a_3    conda-forge
> libiconv                  1.17                 hd590300_2    conda-forge
> libjpeg-turbo             3.0.0                hd590300_1    conda-forge
> libmamba                  1.5.6                had39da4_0    conda-forge
> libmambapy                1.5.6           py311hf2555c7_0    conda-forge
> libnghttp2                1.58.0               h47da74e_1    conda-forge
> libnsl                    2.0.1                hd590300_0    conda-forge
> libpng                    1.6.39               h753d276_0    conda-forge
> librsvg                   2.56.3               he3f83f7_1    conda-forge
> libsodium                 1.0.18               h36c2ea0_1    conda-forge
> libsolv                   0.7.27               hfc55251_0    conda-forge
> libsqlite                 3.44.2               h2797004_0    conda-forge
> libssh2                   1.11.0               h0841786_0    conda-forge
> libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
> libtiff                   4.6.0                ha9c0a0a_2    conda-forge
> libuuid                   2.38.1               h0b41bf4_0    conda-forge
> libuv                     1.46.0               hd590300_0    conda-forge
> libwebp                   1.3.2                h658648e_1    conda-forge
> libwebp-base              1.3.2                hd590300_0    conda-forge
> libxcb                    1.15                 h0b41bf4_0    conda-forge
> libxcrypt                 4.4.36               hd590300_1    conda-forge
> libxml2                   2.12.3               h232c23b_0    conda-forge
> libzlib                   1.2.13               hd590300_5    conda-forge
> lz4-c                     1.9.4                hcb278e6_0    conda-forge
> lzo                       2.10              h516909a_1000    conda-forge
> mako                      1.3.0              pyhd8ed1ab_0    conda-forge
> mamba                     1.5.6           py311h3072747_0    conda-forge
> markupsafe                2.1.3           py311h459d7ec_1    conda-forge
> matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
> menuinst                  2.0.1           py311h38be061_0    conda-forge
> mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
> nb_conda_kernels          2.3.1           py311h38be061_2    conda-forge
> nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
> nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
> nbconvert                 7.13.1             pyhd8ed1ab_0    conda-forge
> nbconvert-core            7.13.1             pyhd8ed1ab_0    conda-forge
> nbconvert-pandoc          7.13.1             pyhd8ed1ab_0    conda-forge
> nbdime                    4.0.1              pyhd8ed1ab_0    conda-forge
> nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
> nbgitpuller               1.2.0                    pypi_0    pypi
> nbgrader                  0.9.1                    pypi_0    pypi
> ncurses                   6.4                  h59595ed_2    conda-forge
> nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
> nodejs                    20.9.0               hb753e55_0    conda-forge
> notebook                  7.0.6              pyhd8ed1ab_0    conda-forge
> notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
> oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
> openjdk                   21.0.1               haa376d0_0    conda-forge
> openssl                   3.2.0                hd590300_1    conda-forge
> overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
> packaging                 23.2               pyhd8ed1ab_0    conda-forge
> pamela                    1.1.0              pyh1a96a4e_0    conda-forge
> pandoc                    3.1.3                h32600fe_0    conda-forge
> pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
> pango                     1.50.14              ha41ecd1_2    conda-forge
> parso                     0.8.3              pyhd8ed1ab_0    conda-forge
> pcre2                     10.42                hcad00b1_0    conda-forge
> pexpect                   4.9.0                    pypi_0    pypi
> pickleshare               0.7.5                   py_1003    conda-forge
> pip                       23.3.2             pyhd8ed1ab_0    conda-forge
> pixman                    0.42.2               h59595ed_0    conda-forge
> pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
> platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
> pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
> prometheus_client         0.19.0             pyhd8ed1ab_0    conda-forge
> prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
> psutil                    5.9.7           py311h459d7ec_0    conda-forge
> pthread-stubs             0.4               h36c2ea0_1001    conda-forge
> ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
> pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
> pybind11-abi              4                    hd8ed1ab_3    conda-forge
> pycosat                   0.6.6           py311h459d7ec_0    conda-forge
> pycparser                 2.21               pyhd8ed1ab_0    conda-forge
> pycrdt                    0.8.2           py311h46250e7_0    conda-forge
> pycrdt-websocket          0.12.6             pyhd8ed1ab_0    conda-forge
> pycurl                    7.45.1          py311hae980a4_3    conda-forge
> pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
> pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
> pyopenssl                 23.3.0             pyhd8ed1ab_0    conda-forge
> pysocks                   1.7.1              pyha2e5f31_6    conda-forge
> python                    3.11.7          hab00c5b_1_cpython    conda-forge
> python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> python-fastjsonschema     2.19.0             pyhd8ed1ab_0    conda-forge
> python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
> python_abi                3.11                    4_cp311    conda-forge
> pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
> pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
> pyzmq                     25.1.2          py311h34ded2d_0    conda-forge
> rapidfuzz                 3.6.1                    pypi_0    pypi
> readline                  8.2                  h8228510_1    conda-forge
> referencing               0.32.0             pyhd8ed1ab_0    conda-forge
> reproc                    14.2.4.post0         hd590300_1    conda-forge
> reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
> requests                  2.31.0             pyhd8ed1ab_0    conda-forge
> rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
> rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
> rpds-py                   0.15.2          py311h46250e7_0    conda-forge
> ruamel.yaml               0.18.5          py311h459d7ec_0    conda-forge
> ruamel.yaml.clib          0.2.7           py311h459d7ec_2    conda-forge
> send2trash                1.8.2              pyh41d4057_0    conda-forge
> setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> smmap                     5.0.1                    pypi_0    pypi
> sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
> soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
> sqlalchemy                2.0.23          py311h459d7ec_0    conda-forge
> stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
> tbx20py                   0.1.0                    pypi_0    pypi
> terminado                 0.18.0             pyh0d859eb_0    conda-forge
> tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
> tk                        8.6.13          noxft_h4845f30_101    conda-forge
> tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
> tornado                   6.3.3           py311h459d7ec_1    conda-forge
> tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
> traitlets                 5.14.0             pyhd8ed1ab_0    conda-forge
> truststore                0.8.0              pyhd8ed1ab_0    conda-forge
> types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
> typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
> typing_extensions         4.9.0              pyha770c72_0    conda-forge
> typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
> tzdata                    2023d                h0c530f3_0    conda-forge
> uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
> urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
> wcwidth                   0.2.12             pyhd8ed1ab_0    conda-forge
> webcolors                 1.13               pyhd8ed1ab_0    conda-forge
> webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
> websocket-client          1.7.0              pyhd8ed1ab_0    conda-forge
> wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
> widgetsnbextension        4.0.9                    pypi_0    pypi
> xorg-fixesproto           5.0               h7f98852_1002    conda-forge
> xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
> xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
> xorg-libice               1.1.1                hd590300_0    conda-forge
> xorg-libsm                1.2.4                h7391055_0    conda-forge
> xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
> xorg-libxau               1.0.11               hd590300_0    conda-forge
> xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
> xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
> xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
> xorg-libxi                1.7.10               h7f98852_0    conda-forge
> xorg-libxrender           0.9.11               hd590300_0    conda-forge
> xorg-libxt                1.3.0                hd590300_1    conda-forge
> xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
> xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
> xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
> xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
> xorg-xproto               7.0.31            h7f98852_1007    conda-forge
> xz                        5.2.6                h166bdaf_0    conda-forge
> yaml                      0.2.5                h7f98852_2    conda-forge
> yaml-cpp                  0.8.0                h59595ed_0    conda-forge
> zeromq                    4.3.5                h59595ed_0    conda-forge
> zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
> zlib                      1.2.13               hd590300_5    conda-forge
> zstandard                 0.22.0          py311haa97af0_0    conda-forge
> zstd                      1.5.5                hfc55251_0    conda-forge

**Comment by himi** [comment]
I do not think JupyterLab 3.x plugins are compatible with 4.x.  That means we need to migrate or recreate it to support 4.x, and it's not a trivial task or easy fix.  I think I can contribute it but I'm afraid it's not a priority in this phase.

**Comment by seidewitz** [comment]
Currently, we are actually only supporting JupyterLab 2.x. It looks like we should be able to move to JupyterLab 3.x without too much trouble. However, as noted by @himi, moving to JupyterLab 3.x is likely more effort than we have resources for right now.

@GorgiAstro, If you would like to discuss this further with the community, please start a conversation in the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release).

**Comment by jcfrench** [comment]
No, this is still problematic. I'm trying to install the SysML V2 jupyterlab prototype on my laptop, and hitting serious compatibility issues during install. 

First, the install.bat file attempts to downgrade Jupyter lab at this line:

call conda install "jupyter-sysml-kernel=%SYSML_VERSION%" python=3.* jupyterlab=2.* graphviz=2.* nodejs=14.* -c conda-forge -y || goto:error

This downgrades jupyterlab & server to 2.3.2 & 1.2.0

Downscript, this warning gets raised:
Conflicting Dependencies:
JupyterLab              Extension      Package
>=4.1.5 <4.2.0          >=2.0.0 <3.0.0 @jupyterlab/application

Not sure how to proceed.

Thanks,
-Jeff

**Comment by Hbmr9000** [comment]
did the plans update? I see good value in making better use of jupyter 4.x as an agentic IDE and produce more capable sysmlv2 agents :)
