### ISSUE TITLE
Swagger scheme not generated

### ISSUE THREAD

**Issue by hellraider01** [Systems-Modeling/SysML-v2-Pilot-Implementation#535]
The swagger scheme is not generating property.

**Comment by seidewitz** [comment]
There is no Swagger schema in this repository. Is you issue with the SysML v2 API and Services implementation?

In any case, if you would like to have help with installation and using of the Pilot Implementation or API and Services, please post to the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release), rather create a GitHub issue.

**Comment by hellraider01** [comment]
Sorry it was a mistake, from the openapi, it don't have shceme version
