### ISSUE TITLE
Question re source for 'org.omg.sysml/src/org/omg/sysml/generation/SysML.uml'

### ISSUE THREAD

**Issue by dhakehurst** [Systems-Modeling/SysML-v2-Pilot-Implementation#544]
Hi,
I see various Commits saying that this file has been 'Regenerated' (e.g. ST6RI-736)

From what source is it generated ?

thanks

**Comment by dhakehurst** [comment]
ok, thanks

**Comment by dhakehurst** [comment]
> are not available publicly. 
what is the reason for not making them available publicly ?

**Comment by seidewitz** [comment]
The source models are work products of the task forces maintaining the standards. Accessing them requires specific tooling and licenses, and it is not practical to support access outside of the groups working on them. However archival snapshots of the models for adopted versions of the standards are available internally as "ancillary artifacts" to all OMG members on the member-only pages for the specifications.
