### ISSUE TITLE
SysML v2 parser

### ISSUE THREAD

**Issue by sbgaia** [Systems-Modeling/SysML-v2-Pilot-Implementation#545]
Hi, 

I am currently delving into this new version of SysML to see if it would make sense to update some SysML v1 models to this new version of the language. I was wondering if there is a SysML v2 parser that could be used to load a SysML v2 model and integrate custom methodologies.

Thanks

**Comment by seidewitz** [comment]
Hi,

The Pilot Implementation does, of course, contain a parser. For information on how to access it programmatically, please join the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release), and then take a look at the post [here](https://groups.google.com/g/sysml-v2-release/c/XOhdgqLTyBI/m/54cXdCEKAgAJ) with the update [here](https://groups.google.com/g/sysml-v2-release/c/XOhdgqLTyBI/m/l3bIbLKMAgAJ). You can ask further questions on that group.

Note that all Pilot Implementation open source code is distributed under the Lesser GNU Public License, which means you are free to link and call it as a library without modification, with no impact on the licensing of your code. However, if you make any modification to the code and re-distribute that with your code, it most also be licensed under the LGPL or GPL.

Thanks.

Ed
